# GENERATED contains a list of files that are generated by the Makefile, and are
# intended to be committed to the repository.
GENERATED += docs/adr/README.md

.PHONY: test
test:
	go test ./...

.PHONY: coverage
coverage: artifacts/coverage/index.html

.PHONY: coverage-open
coverage-open: artifacts/coverage/index.html
	open "$<"

.PHONY: prepare
prepare: test $(GENERATED)

.PHONY: ci
ci: artifacts/coverage/cover.out
	@make --quiet --always-make -- $(GENERATED)
	@echo "checking for out-of-date generated files"
	@!(git status --porcelain -- $(GENERATED) | grep .)

docs/adr/README.md: $(filter-out docs/adr/README.md,$(wildcard docs/adr/*.md))
	adr generate toc -i docs/adr/README.intro.md > "$@"

artifacts/coverage/index.html: artifacts/coverage/cover.out
	go tool cover -html="$<" -o "$@"

.PHONY: artifacts/coverage/cover.out # always rebuild
artifacts/coverage/cover.out: $(GENERATED)
	@mkdir -p $(@D)
	go test -covermode=atomic -coverprofile=$@ ./...
