 # GENERATED contains a list of files that are generated by the Makefile, and are
 # intended to be committed to the repository.
GENERATED += docs/adr/README.md

.PHONY: test
test:
	go test ./...

.PHONY: ci
ci: test
	@make --quiet --always-make -- $(GENERATED)
	@echo "checking for out-of-date generated files"
	@!(git status --porcelain -- $(GENERATED) | grep .)

.PHONY: prepare
prepare: test $(GENERATED)

docs/adr/README.md: $(filter-out docs/adr/README.md,$(wildcard docs/adr/*.md))
	adr generate toc -i docs/adr/README.intro.md > "$@"
